name: Test build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-q2-hello-world:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: set up python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q pipx
        pipx install copier
        pipx inject copier copier_templates_extensions
        pip install -q flake8
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip

    - name: build plugin from default template
      run: |
        copier copy --defaults . .

    - name: Set up Conda
      uses: qiime2-cutlery/setup-miniconda@v3
      with:
        activate-environment: q2-hello-world-qiime2-tiny-dev
        environment-file: q2-hello-world/environment-files/q2-hello-world-qiime2-tiny-dev.yml
        auto-activate-base: false

    - name: Install plugin
      shell: bash -l {0}
      run: |
        cd q2-hello-world
        make install

    - name: Call info on the deployment
      shell: bash -l {0}
      run: |
        qiime info

    - name: Call --help on plugin
      shell: bash -l {0}
      run: |
        qiime hello-world --help

    - name: Test plugin
      shell: bash -l {0}
      run: |
        cd q2-hello-world
        make test

    - name: Lint plugin
      shell: bash -l {0}
      run: |
        cd q2-hello-world
        flake8
        q2lint
